### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by zzt93**
Fix the bug when used in 2016.3, click path choosing caused NPE.
Your original code set tool frame invisible when choosing path, which  make it fail to create dialog (the logic of `DialogWrapperPeerImpl.java` require its father component, i.e. too frame, to be visible). So there exists two ways to solve it:

- make tool frame visible;
- choose another parent component for dialog to use;

I chose the second one to make it consistent with your original behavior.
I only tested on latest version of intellij (2016.1, 2016.3). Is there easy way to test on multiple versions?

### CODE REVIEW

**Comment by misakuo** [comment]
Is all IDE contains the class `WindowManagerEx` ?

**Comment by misakuo** [comment]
Tested on Android Studio 1.5.1 and it works well.
By the way, replace `WindowManagerEx` with `WindowManager` could be better?

**Comment by misakuo** [comment]
I have not maintained this plugin for a long time, maybe you can add some of the long-awaited features for the user, such as generate getter and setter, custom field names, and more……

**Comment by zzt93** [comment]
I am not sure whether replacing `WindowManagerEx` with `WindowManager` could be better, I just saw other part of idea source using `WindowManagerEx` to generate dialog so I mimic that code.

I may consider adding some of them if I have time.

**Comment by zzt93** [comment]
May I refactor your repo structure? like removing those versions of zip?

**Comment by misakuo** [comment]
Method `findVisibleFrame ()` is defined in class`WindowManager`, the `WindowManagerEx` has extended `WindowManager`

**Comment by misakuo** [comment]
Sure, you can do anything you want in your repo and pull request to here

**Comment by misakuo** [comment]
link to #7

**Pull request closed without merging**
